package pl.wojtyna.dslv2.metrics;

public enum Rule {
    MULTI_BC_ELEMENT,
    HIGH_OUTGOING_COUPLING,
    SINGLE_POINT_OF_FAILURE,
    PROCESS_TOO_MANY_BCS,
    PROCESS_TOO_MANY_ELEMENTS,
    ELEMENT_TOO_MANY_RESPONSIBILITIES,
    BC_TOO_MANY_RESPONSIBILITIES,
    BC_HIGH_COUPLING,
    NON_FAVORABLE_RELATIONSHIP,
    ELEMENT_TOO_MANY_PROCESSES,
    BC_TOO_MANY_PROCESSES
}
